/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        secondary: "#0058be",
        "surface-variant": "#e1e3e4",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        tertiary: "#00180d",
        error: "#ba1a1a",
        surface: "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        primary: "#0a1422",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#44474c",
        "surface-container": "#edeeef",
        "on-tertiary-container": "#00a371",
        "on-primary-container": "#8690a1",
        "on-secondary-container": "#fefcff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#1f2937",
        "secondary-container": "#2170e4",
        "tertiary-container": "#002f1e",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#d9e3f6",
        "surface-container-high": "#e7e8e9",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#bdc7d9",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3d4756",
        "surface-tint": "#555f6f",
        "primary-fixed-dim": "#bdc7d9",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#121c2a",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004395",
        outline: "#75777c",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        background: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#c5c6cc",
        "on-tertiary-fixed-variant": "#005236",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "card-padding": "24px",
        margin: "32px",
        unit: "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        h1: ["Inter", "system-ui", "sans-serif"],
        h2: ["Inter", "system-ui", "sans-serif"],
        h3: ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

